// create separate namespace for all the Emscripten stuff.. otherwise naming clashes may occur especially when 
// optimizing using closure compiler..
window.spp_backend_state_gsf= {
	locateFile: function(path, scriptDirectory) { return (typeof window.WASM_SEARCH_PATH == 'undefined') ? path : window.WASM_SEARCH_PATH + path; },
	notReady: true,
	adapterCallback: function(){}	// overwritten later	
};
window.spp_backend_state_gsf["onRuntimeInitialized"] = function() {	// emscripten callback needed in case async init is used (e.g. for WASM)
	this.notReady= false;
	this.adapterCallback();
}.bind(window.spp_backend_state_gsf);

var backend_gsf = (function(Module) {var e;e||(e=typeof Module !== 'undefined' ? Module : {});var aa={},k;for(k in e)e.hasOwnProperty(k)&&(aa[k]=e[k]);e.arguments=[];e.thisProgram="./this.program";e.quit=function(a,b){throw b;};e.preRun=[];e.postRun=[];var ba=!1,l=!1,n=!1,ca=!1;ba="object"===typeof window;l="function"===typeof importScripts;n="object"===typeof process&&"function"===typeof require&&!ba&&!l;ca=!ba&&!n&&!l;var p="";function da(a){return e.locateFile?e.locateFile(a,p):p+a}
if(n){p=__dirname+"/";var ea,fa;e.read=function(a,b){ea||(ea=require("fs"));fa||(fa=require("path"));a=fa.normalize(a);a=ea.readFileSync(a);return b?a:a.toString()};e.readBinary=function(a){a=e.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(e.thisProgram=process.argv[1].replace(/\\/g,"/"));e.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=e);process.on("uncaughtException",function(a){throw a;});process.on("unhandledRejection",
r);e.quit=function(a){process.exit(a)};e.inspect=function(){return"[Emscripten Module object]"}}else if(ca)"undefined"!=typeof read&&(e.read=function(a){return read(a)}),e.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?e.arguments=scriptArgs:"undefined"!=typeof arguments&&(e.arguments=arguments),"function"===typeof quit&&(e.quit=function(a){quit(a)});else if(ba||l)l?
p=self.location.href:document.currentScript&&(p=document.currentScript.src),p=0!==p.indexOf("blob:")?p.substr(0,p.lastIndexOf("/")+1):"",e.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(e.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),e.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==
d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},e.setWindowTitle=function(a){document.title=a};var ha=e.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),t=e.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||ha);for(k in aa)aa.hasOwnProperty(k)&&(e[k]=aa[k]);aa=void 0;function ja(a){var b=u;u=u+a+15&-16;return b}
function ka(a){var b=w[x>>2];a=b+a+15&-16;w[x>>2]=a;if(a=a>=y)la(),a=!0;return a?(w[x>>2]=b,0):b}function ma(a){var b;b||(b=16);return Math.ceil(a/b)*b}var na={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},oa=!1;function assert(a,b){a||r("Assertion failed: "+b)}
var ra={stackSave:function(){z()},stackRestore:function(){A()},arrayToC:function(a){var b=pa(a.length);C.set(a,b);return b},stringToC:function(a){var b=0;if(null!==a&&void 0!==a&&0!==a){var c=(a.length<<2)+1;b=pa(c);qa(a,D,b,c)}return b}},sa={string:ra.stringToC,array:ra.arrayToC};
function ta(a,b){if("number"===typeof a){var c=!0;var d=a}else c=!1,d=a.length;b=4==b?f:["function"===typeof E?E:ja,pa,ja,ka][void 0===b?2:b](Math.max(d,1));if(c){var f=b;assert(0==(b&3));for(a=b+(d&-4);f<a;f+=4)w[f>>2]=0;for(a=b+d;f<a;)C[f++>>0]=0;return b}a.subarray||a.slice?D.set(a,b):D.set(new Uint8Array(a),b);return b}function ua(a){return va?wa?E(a):ka(a):ja(a)}
function F(a,b){if(0===b||!a)return"";for(var c=0,d,f=0;;){d=D[a+f>>0];c|=d;if(0==d&&!b)break;f++;if(b&&f==b)break}b||(b=f);d="";if(128>c){for(;0<b;)c=String.fromCharCode.apply(String,D.subarray(a,a+Math.min(b,1024))),d=d?d+c:c,a+=1024,b-=1024;return d}return xa(a)}var za="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Aa(a,b){for(var c=b;a[c];)++c;if(16<c-b&&a.subarray&&za)return za.decode(a.subarray(b,c));for(c="";;){var d=a[b++];if(!d)return c;if(d&128){var f=a[b++]&63;if(192==(d&224))c+=String.fromCharCode((d&31)<<6|f);else{var g=a[b++]&63;if(224==(d&240))d=(d&15)<<12|f<<6|g;else{var h=a[b++]&63;if(240==(d&248))d=(d&7)<<18|f<<12|g<<6|h;else{var m=a[b++]&63;if(248==(d&252))d=(d&3)<<24|f<<18|g<<12|h<<6|m;else{var q=a[b++]&63;d=(d&1)<<30|f<<24|g<<18|h<<12|m<<6|q}}}65536>d?c+=String.fromCharCode(d):(d-=
65536,c+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else c+=String.fromCharCode(d)}}function xa(a){return Aa(D,a)}
function qa(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var m=a.charCodeAt(++g);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(2097151>=h){if(c+3>=d)break;b[c++]=240|h>>18}else{if(67108863>=h){if(c+4>=d)break;b[c++]=248|h>>24}else{if(c+5>=d)break;b[c++]=252|h>>30;b[c++]=128|h>>24&63}b[c++]=128|h>>18&63}b[c++]=
128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");var buffer,C,D,Ba,w;function Ca(){e.HEAP8=C=new Int8Array(buffer);e.HEAP16=Ba=new Int16Array(buffer);e.HEAP32=w=new Int32Array(buffer);e.HEAPU8=D=new Uint8Array(buffer);e.HEAPU16=new Uint16Array(buffer);e.HEAPU32=new Uint32Array(buffer);e.HEAPF32=new Float32Array(buffer);e.HEAPF64=new Float64Array(buffer)}var Da,u,va,Ea,Fa,Ga,Ha,x;Da=u=Ea=Fa=Ga=Ha=x=0;va=!1;
function la(){r("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+y+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}var Ia=e.TOTAL_STACK||5242880,y=e.TOTAL_MEMORY||67108864;y<Ia&&t("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+y+"! (TOTAL_STACK="+Ia+")");
e.buffer?buffer=e.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(e.wasmMemory=new WebAssembly.Memory({initial:y/65536,maximum:y/65536}),buffer=e.wasmMemory.buffer):buffer=new ArrayBuffer(y),e.buffer=buffer);Ca();function Ja(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.sa;"number"===typeof c?void 0===b.W?e.dynCall_v(c):e.dynCall_vi(c,b.W):c(void 0===b.W?null:b.W)}}}var Ka=[],La=[],Ma=[],Na=[],Oa=[],wa=!1;
function Pa(){var a=e.preRun.shift();Ka.unshift(a)}var G=0,Qa=null,Ra=null;function Sa(){G++;e.monitorRunDependencies&&e.monitorRunDependencies(G)}function Ta(){G--;e.monitorRunDependencies&&e.monitorRunDependencies(G);if(0==G&&(null!==Qa&&(clearInterval(Qa),Qa=null),Ra)){var a=Ra;Ra=null;a()}}e.preloadedImages={};e.preloadedAudios={};function Ua(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(e.wasmBinary)return new Uint8Array(e.wasmBinary);if(e.readBinary)return e.readBinary(f);throw"both async and sync fetching of the wasm failed";}catch(B){r(B)}}function b(){return e.wasmBinary||!ba&&!l||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(f,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+f+"'";return a.arrayBuffer()}).catch(function(){return a()})}function c(a){function c(a){m=a.exports;
if(m.memory){a=m.memory;var b=e.buffer;a.byteLength<b.byteLength&&t("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);e.buffer=buffer=a;Ca()}e.asm=m;e.usingWasm=!0;Ta()}function d(a){c(a.instance)}function g(a){b().then(function(a){return WebAssembly.instantiate(a,h)}).then(a,function(a){t("failed to asynchronously prepare wasm: "+a);r(a)})}if("object"!==typeof WebAssembly)return t("no native wasm support detected"),
!1;if(!(e.wasmMemory instanceof WebAssembly.Memory))return t("no native wasm Memory in use"),!1;a.memory=e.wasmMemory;h.global={NaN:NaN,Infinity:Infinity};h["global.Math"]=Math;h.env=a;Sa();if(e.instantiateWasm)try{return e.instantiateWasm(h,c)}catch(O){return t("Module.instantiateWasm callback failed with error: "+O),!1}e.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||Ua(f)||"function"!==typeof fetch?g(d):WebAssembly.instantiateStreaming(fetch(f,{credentials:"same-origin"}),h).then(d,
function(a){t("wasm streaming compile failed: "+a);t("falling back to ArrayBuffer instantiation");g(d)});return{}}var d="gsf.wast",f="gsf.wasm",g="gsf.temp.asm.js";Ua(d)||(d=da(d));Ua(f)||(f=da(f));Ua(g)||(g=da(g));var h={global:null,env:null,asm2wasm:na,parent:e},m=null;e.asmPreload=e.asm;var q=e.reallocBuffer;e.reallocBuffer=function(a){if("asmjs"===v)var b=q(a);else a:{var c=e.usingWasm?65536:16777216;0<a%c&&(a+=c-a%c);c=e.buffer.byteLength;if(e.usingWasm)try{b=-1!==e.wasmMemory.grow((a-c)/65536)?
e.buffer=e.wasmMemory.buffer:null;break a}catch(ya){b=null;break a}b=void 0}return b};var v="";e.asm=function(a,b){if(!b.table){a=e.wasmTableSize;void 0===a&&(a=1024);var d=e.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==d?new WebAssembly.Table({initial:a,maximum:d,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);e.wasmTable=b.table}b.memoryBase||(b.memoryBase=e.STATIC_BASE);b.tableBase||(b.tableBase=0);b=c(b);
assert(b,"no binaryen method succeeded.");return b}})();Da=1024;u=Da+120064;La.push({sa:function(){Va()}},{sa:function(){Ya()}});e.STATIC_BASE=Da;e.STATIC_BUMP=120064;u+=16;var H={};
function Za(a){if(Za.G){var b=w[a>>2];var c=w[b>>2]}else Za.G=!0,H.USER=H.LOGNAME="web_user",H.PATH="/",H.PWD="/",H.HOME="/home/web_user",H.LANG="C.UTF-8",H._=e.thisProgram,c=ua(1024),b=ua(256),w[b>>2]=c,w[a>>2]=b;a=[];var d=0,f;for(f in H)if("string"===typeof H[f]){var g=f+"="+H[f];a.push(g);d+=g.length}if(1024<d)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(f=0;f<a.length;f++){d=g=a[f];for(var h=c,m=0;m<d.length;++m)C[h++>>0]=d.charCodeAt(m);C[h>>0]=0;w[b+4*f>>2]=c;c+=g.length+1}w[b+
4*a.length>>2]=0}function $a(){return!!$a.G}var ab=0,bb=[],I={};function cb(a){if(!a||I[a])return a;for(var b in I){var c=+b;if(I[c].ia===a)return c}return a}function ___cxa_free_exception(a){try{return db(a)}catch(b){}}
function eb(){var a=ab;if(!a)return(fb(0),0)|0;var b=I[a],c=b.type;if(!c)return(fb(0),a)|0;var d=Array.prototype.slice.call(arguments);e.___cxa_is_pointer_type(c);gb||(gb=E(4));w[gb>>2]=a;a=gb;for(var f=0;f<d.length;f++)if(d[f]&&e.___cxa_can_catch(d[f],c,a))return a=w[a>>2],b.ia=a,(fb(d[f]),a)|0;a=w[a>>2];return(fb(c),a)|0}
var gb,J={F:1,u:2,Fc:3,Bb:4,B:5,ha:6,Ua:7,Zb:8,s:9,ib:10,da:11,Pc:11,Da:12,S:13,ub:14,lc:15,T:16,ea:17,Qc:18,V:19,fa:20,J:21,h:22,Ub:23,Ca:24,C:25,Mc:26,vb:27,hc:28,N:29,Cc:30,Nb:31,vc:32,rb:33,zc:34,cc:42,yb:43,jb:44,Eb:45,Fb:46,Gb:47,Mb:48,Nc:49,Xb:50,Db:51,ob:35,$b:37,$a:52,cb:53,Rc:54,Vb:55,eb:56,fb:57,pb:35,gb:59,jc:60,Yb:61,Jc:62,ic:63,dc:64,ec:65,Bc:66,ac:67,Xa:68,Gc:69,kb:70,wc:71,Pb:72,sb:73,bb:74,qc:76,ab:77,Ac:78,Hb:79,Ib:80,Lb:81,Kb:82,Jb:83,kc:38,ga:39,Qb:36,U:40,rc:95,uc:96,nb:104,Wb:105,
Ya:97,yc:91,oc:88,fc:92,Dc:108,mb:111,Va:98,lb:103,Tb:101,Rb:100,Kc:110,wb:112,xb:113,Ab:115,Za:114,qb:89,Ob:90,xc:93,Ec:94,Wa:99,Sb:102,Cb:106,mc:107,Lc:109,Oc:87,tb:122,Hc:116,pc:95,bc:123,zb:84,sc:75,hb:125,nc:131,tc:130,Ic:86},hb={0:"Success",1:"Not super-user",2:"No such file or directory",3:"No such process",4:"Interrupted system call",5:"I/O error",6:"No such device or address",7:"Arg list too long",8:"Exec format error",9:"Bad file number",10:"No children",11:"No more processes",12:"Not enough core",
13:"Permission denied",14:"Bad address",15:"Block device required",16:"Mount device busy",17:"File exists",18:"Cross-device link",19:"No such device",20:"Not a directory",21:"Is a directory",22:"Invalid argument",23:"Too many open files in system",24:"Too many open files",25:"Not a typewriter",26:"Text file busy",27:"File too large",28:"No space left on device",29:"Illegal seek",30:"Read only file system",31:"Too many links",32:"Broken pipe",33:"Math arg out of domain of func",34:"Math result not representable",
35:"File locking deadlock error",36:"File or path name too long",37:"No record locks available",38:"Function not implemented",39:"Directory not empty",40:"Too many symbolic links",42:"No message of desired type",43:"Identifier removed",44:"Channel number out of range",45:"Level 2 not synchronized",46:"Level 3 halted",47:"Level 3 reset",48:"Link number out of range",49:"Protocol driver not attached",50:"No CSI structure available",51:"Level 2 halted",52:"Invalid exchange",53:"Invalid request descriptor",
54:"Exchange full",55:"No anode",56:"Invalid request code",57:"Invalid slot",59:"Bad font file fmt",60:"Device not a stream",61:"No data (for no delay io)",62:"Timer expired",63:"Out of streams resources",64:"Machine is not on the network",65:"Package not installed",66:"The object is remote",67:"The link has been severed",68:"Advertise error",69:"Srmount error",70:"Communication error on send",71:"Protocol error",72:"Multihop attempted",73:"Cross mount point (not really error)",74:"Trying to read unreadable message",
75:"Value too large for defined data type",76:"Given log. name not unique",77:"f.d. invalid for this operation",78:"Remote address changed",79:"Can   access a needed shared lib",80:"Accessing a corrupted shared lib",81:".lib section in a.out corrupted",82:"Attempting to link in too many libs",83:"Attempting to exec a shared library",84:"Illegal byte sequence",86:"Streams pipe error",87:"Too many users",88:"Socket operation on non-socket",89:"Destination address required",90:"Message too long",91:"Protocol wrong type for socket",
92:"Protocol not available",93:"Unknown protocol",94:"Socket type not supported",95:"Not supported",96:"Protocol family not supported",97:"Address family not supported by protocol family",98:"Address already in use",99:"Address not available",100:"Network interface is not configured",101:"Network is unreachable",102:"Connection reset by network",103:"Connection aborted",104:"Connection reset by peer",105:"No buffer space available",106:"Socket is already connected",107:"Socket is not connected",108:"Can't send after socket shutdown",
109:"Too many references",110:"Connection timed out",111:"Connection refused",112:"Host is down",113:"Host is unreachable",114:"Socket already connected",115:"Connection already in progress",116:"Stale file handle",122:"Quota exceeded",123:"No medium (in tape drive)",125:"Operation canceled",130:"Previous owner died",131:"State not recoverable"};function ib(a){e.___errno_location&&(w[e.___errno_location()>>2]=a);return a}
function jb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function kb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=jb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function lb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function mb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function nb(){var a=Array.prototype.slice.call(arguments,0);return kb(a.join("/"))}function K(a,b){return kb(a+"/"+b)}
function ob(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=jb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var pb=[];function qb(a,b){pb[a]={input:[],output:[],I:b};rb(a,sb)}
var sb={open:function(a){var b=pb[a.node.rdev];if(!b)throw new L(J.V);a.tty=b;a.seekable=!1},close:function(a){a.tty.I.flush(a.tty)},flush:function(a){a.tty.I.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.I.ua)throw new L(J.ha);for(var f=0,g=0;g<d;g++){try{var h=a.tty.I.ua(a.tty)}catch(m){throw new L(J.B);}if(void 0===h&&0===f)throw new L(J.da);if(null===h||void 0===h)break;f++;b[c+g]=h}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.I.aa)throw new L(J.ha);
for(var f=0;f<d;f++)try{a.tty.I.aa(a.tty,b[c+f])}catch(g){throw new L(J.B);}d&&(a.node.timestamp=Date.now());return f}},tb={ua:function(a){if(!a.input.length){var b=null;if(n){var c=new Buffer(256),d=0,f=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{f=fs.openSync("/dev/stdin","r"),g=!0}catch(h){}}try{d=fs.readSync(f,c,0,256,null)}catch(h){if(-1!=h.toString().indexOf("EOF"))d=0;else throw h;}g&&fs.closeSync(f);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=M(b,!0)}return a.input.shift()},aa:function(a,b){null===b||10===b?(ha(Aa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ha(Aa(a.output,0)),a.output=[])}},ub={aa:function(a,b){null===b||10===b?(t(Aa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<
a.output.length&&(t(Aa(a.output,0)),a.output=[])}},N={m:null,j:function(){return N.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new L(J.F);N.m||(N.m={dir:{node:{o:N.c.o,i:N.c.i,lookup:N.c.lookup,K:N.c.K,rename:N.c.rename,unlink:N.c.unlink,rmdir:N.c.rmdir,readdir:N.c.readdir,symlink:N.c.symlink},stream:{A:N.f.A}},file:{node:{o:N.c.o,i:N.c.i},stream:{A:N.f.A,read:N.f.read,write:N.f.write,ja:N.f.ja,ya:N.f.ya,Aa:N.f.Aa}},link:{node:{o:N.c.o,i:N.c.i,
readlink:N.c.readlink},stream:{}},na:{node:{o:N.c.o,i:N.c.i},stream:vb}});c=wb(a,b,c,d);P(c.mode)?(c.c=N.m.dir.node,c.f=N.m.dir.stream,c.b={}):32768===(c.mode&61440)?(c.c=N.m.file.node,c.f=N.m.file.stream,c.g=0,c.b=null):40960===(c.mode&61440)?(c.c=N.m.link.node,c.f=N.m.link.stream):8192===(c.mode&61440)&&(c.c=N.m.na.node,c.f=N.m.na.stream);c.timestamp=Date.now();a&&(a.b[b]=c);return c},Ja:function(a){if(a.b&&a.b.subarray){for(var b=[],c=0;c<a.g;++c)b.push(a.b[c]);return b}return a.b},Uc:function(a){return a.b?
a.b.subarray?a.b.subarray(0,a.g):new Uint8Array(a.b):new Uint8Array},pa:function(a,b){a.b&&a.b.subarray&&b>a.b.length&&(a.b=N.Ja(a),a.g=a.b.length);if(!a.b||a.b.subarray){var c=a.b?a.b.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.b,a.b=new Uint8Array(b),0<a.g&&a.b.set(c.subarray(0,a.g),0))}else for(!a.b&&0<b&&(a.b=[]);a.b.length<b;)a.b.push(0)},Pa:function(a,b){if(a.g!=b)if(0==b)a.b=null,a.g=0;else{if(!a.b||a.b.subarray){var c=a.b;a.b=new Uint8Array(new ArrayBuffer(b));
c&&a.b.set(c.subarray(0,Math.min(b,a.g)))}else if(a.b||(a.b=[]),a.b.length>b)a.b.length=b;else for(;a.b.length<b;)a.b.push(0);a.g=b}},c:{o:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;P(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.g:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.D=4096;b.blocks=Math.ceil(b.size/b.D);return b},
i:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&N.Pa(a,b.size)},lookup:function(){throw xb[J.u];},K:function(a,b,c,d){return N.createNode(a,b,c,d)},rename:function(a,b,c){if(P(a.mode)){try{var d=yb(b,c)}catch(g){}if(d)for(var f in d.b)throw new L(J.ga);}delete a.parent.b[a.name];a.name=c;b.b[c]=a;a.parent=b},unlink:function(a,b){delete a.b[b]},rmdir:function(a,b){var c=yb(a,b),d;for(d in c.b)throw new L(J.ga);delete a.b[b]},readdir:function(a){var b=
[".",".."],c;for(c in a.b)a.b.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=N.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new L(J.h);return a.link}},f:{read:function(a,b,c,d,f){var g=a.node.b;if(f>=a.node.g)return 0;a=Math.min(a.node.g-f,d);assert(0<=a);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&
(!a.b||a.b.subarray)){if(g)return a.b=b.subarray(c,c+d),a.g=d;if(0===a.g&&0===f)return a.b=new Uint8Array(b.subarray(c,c+d)),a.g=d;if(f+d<=a.g)return a.b.set(b.subarray(c,c+d),f),d}N.pa(a,f+d);if(a.b.subarray&&b.subarray)a.b.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.b[f+g]=b[c+g];a.g=Math.max(a.g,f+d);return d},A:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.g);if(0>b)throw new L(J.h);return b},ja:function(a,b,c){N.pa(a.node,b+c);a.node.g=Math.max(a.node.g,
b+c)},ya:function(a,b,c,d,f,g,h){if(32768!==(a.node.mode&61440))throw new L(J.V);c=a.node.b;if(h&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<f||f+d<a.node.g)c.subarray?c=c.subarray(f,f+d):c=Array.prototype.slice.call(c,f,f+d);a=!0;d=E(d);if(!d)throw new L(J.Da);b.set(c,d)}else a=!1,d=c.byteOffset;return{Oa:d,Sc:a}},Aa:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new L(J.V);if(f&2)return 0;N.f.write(a,b,0,d,c,!1);return 0}}},Q={P:!1,Sa:function(){Q.P=!!process.platform.match(/^win/);var a=
process.binding("constants");a.fs&&(a=a.fs);Q.qa={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},ka:function(a){return Buffer.G?Buffer.from(a):new Buffer(a)},j:function(a){assert(n);return Q.createNode(null,"/",Q.ta(a.$.root),0)},createNode:function(a,b,c){if(!P(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new L(J.h);a=wb(a,b,c);a.c=Q.c;a.f=Q.f;return a},ta:function(a){try{var b=fs.lstatSync(a);Q.P&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;
throw new L(J[c.code]);}return b.mode},l:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.j.$.root);b.reverse();return nb.apply(null,b)},Ia:function(a){a&=-2656257;var b=0,c;for(c in Q.qa)a&c&&(b|=Q.qa[c],a^=c);if(a)throw new L(J.h);return b},c:{o:function(a){a=Q.l(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new L(J[c.code]);}Q.P&&!b.D&&(b.D=4096);Q.P&&!b.blocks&&(b.blocks=(b.size+b.D-1)/b.D|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,
gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,D:b.D,blocks:b.blocks}},i:function(a,b){var c=Q.l(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new L(J[d.code]);}},lookup:function(a,b){var c=K(Q.l(a),b);c=Q.ta(c);return Q.createNode(a,b,c)},K:function(a,b,c,d){a=Q.createNode(a,b,c,d);b=Q.l(a);try{P(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(f){if(!f.code)throw f;
throw new L(J[f.code]);}return a},rename:function(a,b,c){a=Q.l(a);b=K(Q.l(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new L(J[d.code]);}},unlink:function(a,b){a=K(Q.l(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new L(J[c.code]);}},rmdir:function(a,b){a=K(Q.l(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new L(J[c.code]);}},readdir:function(a){a=Q.l(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new L(J[b.code]);}},symlink:function(a,
b,c){a=K(Q.l(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new L(J[d.code]);}},readlink:function(a){var b=Q.l(a);try{return b=fs.readlinkSync(b),b=zb.relative(zb.resolve(a.j.$.root),b)}catch(c){if(!c.code)throw c;throw new L(J[c.code]);}}},f:{open:function(a){var b=Q.l(a.node);try{32768===(a.node.mode&61440)&&(a.M=fs.openSync(b,Q.Ia(a.flags)))}catch(c){if(!c.code)throw c;throw new L(J[c.code]);}},close:function(a){try{32768===(a.node.mode&61440)&&a.M&&fs.closeSync(a.M)}catch(b){if(!b.code)throw b;
throw new L(J[b.code]);}},read:function(a,b,c,d,f){if(0===d)return 0;try{return fs.readSync(a.M,Q.ka(b.buffer),c,d,f)}catch(g){throw new L(J[g.code]);}},write:function(a,b,c,d,f){try{return fs.writeSync(a.M,Q.ka(b.buffer),c,d,f)}catch(g){throw new L(J[g.code]);}},A:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.M).size}catch(d){throw new L(J[d.code]);}if(0>b)throw new L(J.h);return b}}};u+=16;u+=16;u+=16;
var Ab=null,Bb={},R=[],Cb=1,S=null,Db=!0,T={},L=null,xb={};
function U(a,b){a=ob("/",a);b=b||{};if(!a)return{path:"",node:null};var c={ra:!0,ba:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.ba)throw new L(J.U);a=jb(a.split("/").filter(function(a){return!!a}),!1);var f=Ab;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=yb(f,a[d]);c=K(c,a[d]);f.L&&(!g||g&&b.ra)&&(f=f.L.root);if(!g||b.X)for(g=0;40960===(f.mode&61440);)if(f=Eb(c),c=ob(lb(c),f),f=U(c,{ba:b.ba}).node,40<g++)throw new L(J.U);}return{path:c,node:f}}
function V(a){for(var b;;){if(a===a.parent)return a=a.j.za,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Fb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%S.length}function Gb(a){var b=Fb(a.parent.id,a.name);a.H=S[b];S[b]=a}function yb(a,b){var c;if(c=(c=Hb(a,"x"))?c:a.c.lookup?0:J.S)throw new L(c,a);for(c=S[Fb(a.id,b)];c;c=c.H){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.c.lookup(a,b)}
function wb(a,b,c,d){Ib||(Ib=function(a,b,c,d){a||(a=this);this.parent=a;this.j=a.j;this.L=null;this.id=Cb++;this.name=b;this.mode=c;this.c={};this.f={};this.rdev=d},Ib.prototype={},Object.defineProperties(Ib.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Ma:{get:function(){return P(this.mode)}},La:{get:function(){return 8192===(this.mode&
61440)}}}));a=new Ib(a,b,c,d);Gb(a);return a}function P(a){return 16384===(a&61440)}var Jb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Kb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Hb(a,b){if(Db)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return J.S}else return J.S;return 0}
function Lb(a,b){try{return yb(a,b),J.ea}catch(c){}return Hb(a,"wx")}function Mb(a){var b=4096;for(a=a||0;a<=b;a++)if(!R[a])return a;throw new L(J.Ca);}function Nb(a,b){Ob||(Ob=function(){},Ob.prototype={},Object.defineProperties(Ob.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Ob,d;for(d in a)c[d]=a[d];a=c;b=Mb(b);a.fd=b;return R[b]=a}var vb={open:function(a){a.f=Bb[a.node.rdev].f;a.f.open&&a.f.open(a)},A:function(){throw new L(J.N);}};
function rb(a,b){Bb[a]={f:b}}function Pb(a,b){var c="/"===b,d=!b;if(c&&Ab)throw new L(J.T);if(!c&&!d){var f=U(b,{ra:!1});b=f.path;f=f.node;if(f.L)throw new L(J.T);if(!P(f.mode))throw new L(J.fa);}b={type:a,$:{},za:b,Na:[]};a=a.j(b);a.j=b;b.root=a;c?Ab=a:f&&(f.L=b,f.j&&f.j.Na.push(b))}function Qb(a,b,c){var d=U(a,{parent:!0}).node;a=mb(a);if(!a||"."===a||".."===a)throw new L(J.h);var f=Lb(d,a);if(f)throw new L(f);if(!d.c.K)throw new L(J.F);return d.c.K(d,a,b,c)}
function W(a,b){return Qb(a,(void 0!==b?b:511)&1023|16384,0)}function Rb(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Qb(a,b|8192,c)}function Sb(a,b){if(!ob(a))throw new L(J.u);var c=U(b,{parent:!0}).node;if(!c)throw new L(J.u);b=mb(b);var d=Lb(c,b);if(d)throw new L(d);if(!c.c.symlink)throw new L(J.F);return c.c.symlink(c,b,a)}
function Tb(a){var b=U(a,{parent:!0}).node,c=mb(a),d=yb(b,c);a:{try{var f=yb(b,c)}catch(h){f=h.v;break a}var g=Hb(b,"wx");f=g?g:P(f.mode)?J.J:0}if(f)throw new L(f);if(!b.c.unlink)throw new L(J.F);if(d.L)throw new L(J.T);try{T.willDeletePath&&T.willDeletePath(a)}catch(h){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+h.message)}b.c.unlink(b,c);b=Fb(d.parent.id,d.name);if(S[b]===d)S[b]=d.H;else for(b=S[b];b;){if(b.H===d){b.H=d.H;break}b=b.H}try{if(T.onDeletePath)T.onDeletePath(a)}catch(h){console.log("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+h.message)}}function Eb(a){a=U(a).node;if(!a)throw new L(J.u);if(!a.c.readlink)throw new L(J.h);return ob(V(a.parent),a.c.readlink(a))}function Ub(a,b){var c;"string"===typeof a?c=U(a,{X:!0}).node:c=a;if(!c.c.i)throw new L(J.F);c.c.i(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function Vb(a,b,c,d){if(""===a)throw new L(J.u);if("string"===typeof b){var f=Jb[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=kb(a);try{g=U(a,{X:!(b&131072)}).node}catch(q){}}f=!1;if(b&64)if(g){if(b&128)throw new L(J.ea);}else g=Qb(a,c,0),f=!0;if(!g)throw new L(J.u);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&!P(g.mode))throw new L(J.fa);if(!f){var h=g?40960===(g.mode&61440)?J.U:
P(g.mode)&&("r"!==Kb(b)||b&512)?J.J:Hb(g,Kb(b)):J.u;if(h)throw new L(h);}if(b&512){c=g;var m;"string"===typeof c?m=U(c,{X:!0}).node:m=c;if(!m.c.i)throw new L(J.F);if(P(m.mode))throw new L(J.J);if(32768!==(m.mode&61440))throw new L(J.h);if(c=Hb(m,"w"))throw new L(c);m.c.i(m,{size:0,timestamp:Date.now()})}b&=-641;d=Nb({node:g,path:V(g),flags:b,seekable:!0,position:0,f:g.f,Ta:[],error:!1},d);d.f.open&&d.f.open(d);!e.logReadFiles||b&1||(Wb||(Wb={}),a in Wb||(Wb[a]=1,h("read file: "+a)));try{T.onOpenFile&&
(h=0,1!==(b&2097155)&&(h|=1),0!==(b&2097155)&&(h|=2),T.onOpenFile(a,h))}catch(q){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+q.message)}return d}function Xb(a){if(null===a.fd)throw new L(J.s);a.Y&&(a.Y=null);try{a.f.close&&a.f.close(a)}catch(b){throw b;}finally{R[a.fd]=null}a.fd=null}function Yb(a,b,c){if(null===a.fd)throw new L(J.s);if(!a.seekable||!a.f.A)throw new L(J.N);a.position=a.f.A(a,b,c);a.Ta=[]}
function Zb(a,b,c,d,f,g){if(0>d||0>f)throw new L(J.h);if(null===a.fd)throw new L(J.s);if(0===(a.flags&2097155))throw new L(J.s);if(P(a.node.mode))throw new L(J.J);if(!a.f.write)throw new L(J.h);a.flags&1024&&Yb(a,0,2);var h="undefined"!==typeof f;if(!h)f=a.position;else if(!a.seekable)throw new L(J.N);b=a.f.write(a,b,c,d,f,g);h||(a.position+=b);try{if(a.path&&T.onWriteToFile)T.onWriteToFile(a.path)}catch(m){console.log("FS.trackingDelegate['onWriteToFile']('"+path+"') threw an exception: "+m.message)}return b}
function $b(){L||(L=function(a,b){this.node=b;this.Ra=function(a){this.v=a;for(var b in J)if(J[b]===a){this.code=b;break}};this.Ra(a);this.message=hb[a];this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},L.prototype=Error(),L.prototype.constructor=L,[J.u].forEach(function(a){xb[a]=new L(a);xb[a].stack="<generic error, no stack>"}))}var ac;function bc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function cc(a,b,c,d){a=K("string"===typeof a?a:V(a),b);return W(a,bc(c,d))}function dc(a,b){a="string"===typeof a?a:V(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=K(a,c);try{W(d)}catch(f){}a=d}}return d}function ec(a,b,c,d){a=K("string"===typeof a?a:V(a),b);c=bc(c,d);return Qb(a,(void 0!==c?c:438)&4095|32768,0)}
function fc(a,b,c,d,f,g){a=b?K("string"===typeof a?a:V(a),b):a;d=bc(d,f);f=Qb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}Ub(f,d|146);a=Vb(f,"w");Zb(a,c,0,c.length,0,g);Xb(a);Ub(f,d)}return f}
function X(a,b,c,d){a=K("string"===typeof a?a:V(a),b);b=bc(!!c,!!d);X.wa||(X.wa=64);var f=X.wa++<<8|0;rb(f,{open:function(a){a.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(a,b,d,f){for(var g=0,h=0;h<f;h++){try{var m=c()}catch(Xa){throw new L(J.B);}if(void 0===m&&0===g)throw new L(J.da);if(null===m||void 0===m)break;g++;b[d+h]=m}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,c,f){for(var g=0;g<f;g++)try{d(b[c+g])}catch(B){throw new L(J.B);}f&&(a.node.timestamp=
Date.now());return g}});return Rb(a,b,f)}function hc(a,b,c){a=K("string"===typeof a?a:V(a),b);return Sb(c,a)}
function ic(a){if(a.La||a.Ma||a.link||a.b)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(e.read)try{a.b=M(e.read(a.url),!0),a.g=a.b.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||ib(J.B);return b}
function jc(a,b,c,d,f){function g(){this.Z=!1;this.O=[]}g.prototype.get=function(a){if(!(a>this.length-1||0>a)){var b=a%this.chunkSize;return this.va(a/this.chunkSize|0)[b]}};g.prototype.Qa=function(a){this.va=a};g.prototype.la=function(){var a=new XMLHttpRequest;a.open("HEAD",c,!1);a.send(null);if(!(200<=a.status&&300>a.status||304===a.status))throw Error("Couldn't load "+c+". Status: "+a.status);var b=Number(a.getResponseHeader("Content-length")),d,f=(d=a.getResponseHeader("Accept-Ranges"))&&"bytes"===
d;a=(d=a.getResponseHeader("Content-Encoding"))&&"gzip"===d;var g=1048576;f||(g=b);var h=this;h.Qa(function(a){var d=a*g,f=(a+1)*g-1;f=Math.min(f,b-1);if("undefined"===typeof h.O[a]){var m=h.O;if(d>f)throw Error("invalid range ("+d+", "+f+") or no bytes requested!");if(f>b-1)throw Error("only "+b+" bytes available! programmer error!");var q=new XMLHttpRequest;q.open("GET",c,!1);b!==g&&q.setRequestHeader("Range","bytes="+d+"-"+f);"undefined"!=typeof Uint8Array&&(q.responseType="arraybuffer");q.overrideMimeType&&
q.overrideMimeType("text/plain; charset=x-user-defined");q.send(null);if(!(200<=q.status&&300>q.status||304===q.status))throw Error("Couldn't load "+c+". Status: "+q.status);d=void 0!==q.response?new Uint8Array(q.response||[]):M(q.responseText||"",!0);m[a]=d}if("undefined"===typeof h.O[a])throw Error("doXHR failed!");return h.O[a]});if(a||!b)g=b=1,g=b=this.va(0).length,console.log("LazyFiles on gzip forces download of the whole file when length is accessed");this.Fa=b;this.Ea=g;this.Z=!0};if("undefined"!==
typeof XMLHttpRequest){if(!l)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new g;Object.defineProperties(h,{length:{get:function(){this.Z||this.la();return this.Fa}},chunkSize:{get:function(){this.Z||this.la();return this.Ea}}});var m=void 0}else m=c,h=void 0;var q=ec(a,b,d,f);h?q.b=h:m&&(q.b=null,q.url=m);Object.defineProperties(q,{g:{get:function(){return this.b.length}}});var v={};Object.keys(q.f).forEach(function(a){var b=
q.f[a];v[a]=function(){if(!ic(q))throw new L(J.B);return b.apply(null,arguments)}});v.read=function(a,b,c,d,f){if(!ic(q))throw new L(J.B);a=a.node.b;if(f>=a.length)return 0;d=Math.min(a.length-f,d);assert(0<=d);if(a.slice)for(var g=0;g<d;g++)b[c+g]=a[f+g];else for(g=0;g<d;g++)b[c+g]=a.get(f+g);return d};q.f=v;return q}
function kc(a,b,c,d,f,g,h,m,q,v){function B(c){function B(c){v&&v();m||fc(a,b,c,d,f,q);g&&g();Ta()}var O=!1;e.preloadPlugins.forEach(function(a){!O&&a.canHandle(ia)&&(a.handle(c,ia,B,function(){h&&h();Ta()}),O=!0)});O||B(c)}Browser.Vc();var ia=b?ob(K(a,b)):a;Sa();"string"==typeof c?Browser.Tc(c,function(a){B(a)},h):B(c)}var FS={},Ib,Ob,Wb,Y=0;function Z(){Y+=4;return w[Y-4>>2]}function lc(){var a=R[Z()];if(!a)throw new L(J.s);return a}ta(M("GMT"),2);
function mc(){function a(a){return(a=a.toTimeString().match(/\(([A-Za-z ]+)\)$/))?a[1]:"GMT"}if(!nc){nc=!0;w[oc()>>2]=60*(new Date).getTimezoneOffset();var b=new Date(2E3,0,1),c=new Date(2E3,6,1);w[pc()>>2]=Number(b.getTimezoneOffset()!=c.getTimezoneOffset());var d=a(b),f=a(c);d=ta(M(d),0);f=ta(M(f),0);c.getTimezoneOffset()<b.getTimezoneOffset()?(w[qc()>>2]=d,w[qc()+4>>2]=f):(w[qc()>>2]=f,w[qc()+4>>2]=d)}}var nc;$b();S=Array(4096);Pb(N,"/");W("/tmp");W("/home");W("/home/web_user");
(function(){W("/dev");rb(259,{read:function(){return 0},write:function(a,b,f,g){return g}});Rb("/dev/null",259);qb(1280,tb);qb(1536,ub);Rb("/dev/tty",1280);Rb("/dev/tty1",1536);if("undefined"!==typeof crypto){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else n?b=function(){return require("crypto").randomBytes(1)[0]}:b=function(){r("random_device")};X("/dev","random",b);X("/dev","urandom",b);W("/dev/shm");W("/dev/shm/tmp")})();W("/proc");W("/proc/self");W("/proc/self/fd");
Pb({j:function(){var a=wb("/proc/self","fd",16895,73);a.c={lookup:function(a,c){var b=R[+c];if(!b)throw new L(J.s);a={parent:null,j:{za:"fake"},c:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");
La.unshift(function(){if(!e.noFSInit&&!ac){assert(!ac,"FS.init was previously called. If you want to initialize later with custom parameters, remove any earlier calls (note that one is automatically added to the generated code)");ac=!0;$b();e.stdin=e.stdin;e.stdout=e.stdout;e.stderr=e.stderr;e.stdin?X("/dev","stdin",e.stdin):Sb("/dev/tty","/dev/stdin");e.stdout?X("/dev","stdout",null,e.stdout):Sb("/dev/tty","/dev/stdout");e.stderr?X("/dev","stderr",null,e.stderr):Sb("/dev/tty1","/dev/stderr");var a=
Vb("/dev/stdin","r");assert(0===a.fd,"invalid handle for stdin ("+a.fd+")");a=Vb("/dev/stdout","w");assert(1===a.fd,"invalid handle for stdout ("+a.fd+")");a=Vb("/dev/stderr","w");assert(2===a.fd,"invalid handle for stderr ("+a.fd+")")}});Ma.push(function(){Db=!1});Na.push(function(){ac=!1;var a=e._fflush;a&&a(0);for(a=0;a<R.length;a++){var b=R[a];b&&Xb(b)}});e.FS_createFolder=cc;e.FS_createPath=dc;e.FS_createDataFile=fc;e.FS_createPreloadedFile=kc;e.FS_createLazyFile=jc;e.FS_createLink=hc;
e.FS_createDevice=X;e.FS_unlink=Tb;La.unshift(function(){});Na.push(function(){});if(n){var fs=require("fs"),zb=require("path");Q.Sa()}x=ja(4);Ea=Fa=ma(u);Ga=Ea+Ia;Ha=ma(Ga);w[x>>2]=Ha;va=!0;function M(a,b){for(var c=0,d=0;d<a.length;++d){var f=a.charCodeAt(d);55296<=f&&57343>=f&&(f=65536+((f&1023)<<10)|a.charCodeAt(++d)&1023);127>=f?++c:c=2047>=f?c+2:65535>=f?c+3:2097151>=f?c+4:67108863>=f?c+5:c+6}c=Array(c+1);a=qa(a,c,0,c.length);b&&(c.length=a);return c}e.wasmTableSize=3440;
e.wasmMaxTableSize=3440;e.Ga={};
e.Ha={abort:r,enlargeMemory:function(){la()},getTotalMemory:function(){return y},abortOnCannotGrowMemory:la,invoke_ii:function(a,b){var c=z();try{return e.dynCall_ii(a,b)}catch(d){A(c);if("number"!==typeof d&&"longjmp"!==d)throw d;e.setThrew(1,0)}},invoke_iiii:function(a,b,c,d){var f=z();try{return e.dynCall_iiii(a,b,c,d)}catch(g){A(f);if("number"!==typeof g&&"longjmp"!==g)throw g;e.setThrew(1,0)}},invoke_v:function(a){var b=z();try{e.dynCall_v(a)}catch(c){A(b);if("number"!==typeof c&&"longjmp"!==
c)throw c;e.setThrew(1,0)}},invoke_vi:function(a,b){var c=z();try{e.dynCall_vi(a,b)}catch(d){A(c);if("number"!==typeof d&&"longjmp"!==d)throw d;e.setThrew(1,0)}},invoke_vii:function(a,b,c){var d=z();try{e.dynCall_vii(a,b,c)}catch(f){A(d);if("number"!==typeof f&&"longjmp"!==f)throw f;e.setThrew(1,0)}},invoke_viii:function(a,b,c,d){var f=z();try{e.dynCall_viii(a,b,c,d)}catch(g){A(f);if("number"!==typeof g&&"longjmp"!==g)throw g;e.setThrew(1,0)}},invoke_viiii:function(a,b,c,d,f){var g=z();try{e.dynCall_viiii(a,
b,c,d,f)}catch(h){A(g);if("number"!==typeof h&&"longjmp"!==h)throw h;e.setThrew(1,0)}},___assert_fail:function(a,b,c,d){r("Assertion failed: "+F(a)+", at: "+[b?F(b):"unknown filename",c,d?F(d):"unknown function"])},___buildEnvironment:Za,___cxa_allocate_exception:function(a){return E(a)},___cxa_begin_catch:function(a){var b=I[a];b&&!b.ma&&(b.ma=!0,$a.G--);b&&(b.Ba=!1);bb.push(a);(b=cb(a))&&I[b].R++;return a},___cxa_end_catch:function(){e.setThrew(0);var a=bb.pop();if(a){if(a=cb(a)){var b=I[a];assert(0<
b.R);b.R--;0!==b.R||b.Ba||(b.oa&&e.dynCall_vi(b.oa,a),delete I[a],___cxa_free_exception(a))}ab=0}},___cxa_find_matching_catch_2:function(){return eb.apply(null,arguments)},___cxa_find_matching_catch_3:function(){return eb.apply(null,arguments)},___cxa_free_exception:___cxa_free_exception,___cxa_throw:function(a,b,c){I[a]={Oa:a,ia:a,type:b,oa:c,R:0,ma:!1,Ba:!1};ab=a;"uncaught_exception"in $a?$a.G++:$a.G=1;throw a;},___lock:function(){},___resumeException:function(a){ab||(ab=a);throw a;},___setErrNo:ib,
___syscall140:function(a,b){Y=b;try{var c=lc();Z();var d=Z(),f=Z(),g=Z();Yb(c,d,g);w[f>>2]=c.position;c.Y&&0===d&&0===g&&(c.Y=null);return 0}catch(h){return"undefined"!==typeof FS&&h instanceof L||r(h),-h.v}},___syscall145:function(a,b){Y=b;try{var c=lc(),d=Z();a:{var f=Z();for(b=a=0;b<f;b++){var g=w[d+(8*b+4)>>2],h=c,m=w[d+8*b>>2],q=g,v=void 0,B=C;if(0>q||0>v)throw new L(J.h);if(null===h.fd)throw new L(J.s);if(1===(h.flags&2097155))throw new L(J.s);if(P(h.node.mode))throw new L(J.J);if(!h.f.read)throw new L(J.h);
var ia="undefined"!==typeof v;if(!ia)v=h.position;else if(!h.seekable)throw new L(J.N);var Xa=h.f.read(h,B,m,q,v);ia||(h.position+=Xa);var ya=Xa;if(0>ya){var O=-1;break a}a+=ya;if(ya<g)break}O=a}return O}catch(Wa){return"undefined"!==typeof FS&&Wa instanceof L||r(Wa),-Wa.v}},___syscall146:function(a,b){Y=b;try{var c=lc(),d=Z();a:{var f=Z();for(b=a=0;b<f;b++){var g=Zb(c,C,w[d+8*b>>2],w[d+(8*b+4)>>2],void 0);if(0>g){var h=-1;break a}a+=g}h=a}return h}catch(m){return"undefined"!==typeof FS&&m instanceof
L||r(m),-m.v}},___syscall221:function(a,b){Y=b;try{var c=lc();switch(Z()){case 0:var d=Z();return 0>d?-J.h:Vb(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=Z(),c.flags|=d,0;case 12:case 12:return d=Z(),Ba[d+0>>1]=2,0;case 13:case 14:case 13:case 14:return 0;case 16:case 8:return-J.h;case 9:return ib(J.h),-1;default:return-J.h}}catch(f){return"undefined"!==typeof FS&&f instanceof L||r(f),-f.v}},___syscall5:function(a,b){Y=b;try{var c=F(Z()),d=Z(),f=Z();return Vb(c,
d,f).fd}catch(g){return"undefined"!==typeof FS&&g instanceof L||r(g),-g.v}},___syscall54:function(a,b){Y=b;try{var c=lc(),d=Z();switch(d){case 21509:case 21505:return c.tty?0:-J.C;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-J.C;case 21519:if(!c.tty)return-J.C;var f=Z();return w[f>>2]=0;case 21520:return c.tty?-J.h:-J.C;case 21531:a=f=Z();if(!c.f.Ka)throw new L(J.C);return c.f.Ka(c,d,a);case 21523:return c.tty?0:-J.C;case 21524:return c.tty?0:-J.C;default:r("bad ioctl syscall "+
d)}}catch(g){return"undefined"!==typeof FS&&g instanceof L||r(g),-g.v}},___syscall6:function(a,b){Y=b;try{var c=lc();Xb(c);return 0}catch(d){return"undefined"!==typeof FS&&d instanceof L||r(d),-d.v}},___unlock:function(){},_abort:function(){e.abort()},_ems_request_file:function(a){var b=window.ScriptNodePlayer.getInstance();if(b.isReady())return b._fileRequestCallback(a);window.console.log("error: ems_request_file not ready")},_emscripten_memcpy_big:function(a,b,c){D.set(D.subarray(b,b+c),a);return a},
_llvm_exp2_f32:function(a){return Math.pow(2,a)},_localtime_r:function(a,b){mc();a=new Date(1E3*w[a>>2]);w[b>>2]=a.getSeconds();w[b+4>>2]=a.getMinutes();w[b+8>>2]=a.getHours();w[b+12>>2]=a.getDate();w[b+16>>2]=a.getMonth();w[b+20>>2]=a.getFullYear()-1900;w[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);w[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;w[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(2E3,6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,
d))|0;w[b+32>>2]=a;a=w[qc()+(a?4:0)>>2];w[b+40>>2]=a;return b},_time:function(a){var b=Date.now()/1E3|0;a&&(w[a>>2]=b);return b},DYNAMICTOP_PTR:x,STACKTOP:Fa};var rc=e.asm(e.Ga,e.Ha,buffer);e.asm=rc;var Va=e.__GLOBAL__sub_I_gsfplug_cpp=function(){return e.asm.__GLOBAL__sub_I_gsfplug_cpp.apply(null,arguments)};e.___cxa_can_catch=function(){return e.asm.___cxa_can_catch.apply(null,arguments)};e.___cxa_is_pointer_type=function(){return e.asm.___cxa_is_pointer_type.apply(null,arguments)};
var Ya=e.___emscripten_environ_constructor=function(){return e.asm.___emscripten_environ_constructor.apply(null,arguments)};e.___errno_location=function(){return e.asm.___errno_location.apply(null,arguments)};var pc=e.__get_daylight=function(){return e.asm.__get_daylight.apply(null,arguments)},oc=e.__get_timezone=function(){return e.asm.__get_timezone.apply(null,arguments)},qc=e.__get_tzname=function(){return e.asm.__get_tzname.apply(null,arguments)};
e._emu_compute_audio_samples=function(){return e.asm._emu_compute_audio_samples.apply(null,arguments)};e._emu_get_audio_buffer=function(){return e.asm._emu_get_audio_buffer.apply(null,arguments)};e._emu_get_audio_buffer_length=function(){return e.asm._emu_get_audio_buffer_length.apply(null,arguments)};e._emu_get_current_position=function(){return e.asm._emu_get_current_position.apply(null,arguments)};e._emu_get_max_position=function(){return e.asm._emu_get_max_position.apply(null,arguments)};
e._emu_get_sample_rate=function(){return e.asm._emu_get_sample_rate.apply(null,arguments)};e._emu_get_track_info=function(){return e.asm._emu_get_track_info.apply(null,arguments)};e._emu_load_file=function(){return e.asm._emu_load_file.apply(null,arguments)};e._emu_seek_position=function(){return e.asm._emu_seek_position.apply(null,arguments)};e._emu_set_boost=function(){return e.asm._emu_set_boost.apply(null,arguments)};e._emu_set_subsong=function(){return e.asm._emu_set_subsong.apply(null,arguments)};
e._emu_teardown=function(){return e.asm._emu_teardown.apply(null,arguments)};var db=e._free=function(){return e.asm._free.apply(null,arguments)},E=e._malloc=function(){return e.asm._malloc.apply(null,arguments)},fb=e.setTempRet0=function(){return e.asm.setTempRet0.apply(null,arguments)};e.setThrew=function(){return e.asm.setThrew.apply(null,arguments)};
var pa=e.stackAlloc=function(){return e.asm.stackAlloc.apply(null,arguments)},A=e.stackRestore=function(){return e.asm.stackRestore.apply(null,arguments)},z=e.stackSave=function(){return e.asm.stackSave.apply(null,arguments)};e.dynCall_ii=function(){return e.asm.dynCall_ii.apply(null,arguments)};e.dynCall_iiii=function(){return e.asm.dynCall_iiii.apply(null,arguments)};e.dynCall_v=function(){return e.asm.dynCall_v.apply(null,arguments)};e.dynCall_vi=function(){return e.asm.dynCall_vi.apply(null,arguments)};
e.dynCall_vii=function(){return e.asm.dynCall_vii.apply(null,arguments)};e.dynCall_viii=function(){return e.asm.dynCall_viii.apply(null,arguments)};e.dynCall_viiii=function(){return e.asm.dynCall_viiii.apply(null,arguments)};e.asm=rc;
e.ccall=function(a,b,c,d){var f=e["_"+a];assert(f,"Cannot call unknown function "+a+", make sure it is exported");var g=[];a=0;if(d)for(var h=0;h<d.length;h++){var m=sa[c[h]];m?(0===a&&(a=z()),g[h]=m(d[h])):g[h]=d[h]}c=f.apply(null,g);c="string"===b?F(c):"boolean"===b?!!c:c;0!==a&&A(a);return c};e.getMemory=ua;e.Pointer_stringify=F;e.UTF8ToString=xa;e.addRunDependency=Sa;e.removeRunDependency=Ta;e.FS_createFolder=cc;e.FS_createPath=dc;e.FS_createDataFile=fc;e.FS_createPreloadedFile=kc;
e.FS_createLazyFile=jc;e.FS_createLink=hc;e.FS_createDevice=X;e.FS_unlink=Tb;Ra=function sc(){e.calledRun||tc();e.calledRun||(Ra=sc)};
function tc(){function a(){if(!e.calledRun&&(e.calledRun=!0,!oa)){wa||(wa=!0,Ja(La));Ja(Ma);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var a=e.postRun.shift();Oa.unshift(a)}Ja(Oa)}}if(!(0<G)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Pa();Ja(Ka);0<G||e.calledRun||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},
1);a()},1)):a())}}e.run=tc;function r(a){if(e.onAbort)e.onAbort(a);void 0!==a?(ha(a),t(a),a=JSON.stringify(a)):a="";oa=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}e.abort=r;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();e.noExitRuntime=!0;tc();
  return {
	Module: Module,  // expose original Module
  };
})(window.spp_backend_state_gsf);
/*
 gsf_adapter.js: Adapts "GSF decoder" backend to generic WebAudio/ScriptProcessor player.

    version 1.1
 	copyright (C) 2018-2023 Juergen Wothke


 note: copy/paste of respective 2sf_adapter (see webDS)

 LICENSE

   This library is distributed under the Mozilla Public License version 2.0. A copy of
   the license is available in the distributed LICENSE file.
*/
class GSFBackendAdapter extends EmsHEAP16BackendAdapter {
	constructor(modlandMode)
	{
		super(backend_gsf.Module, 2, new SimpleFileMapper(backend_gsf.Module));
		
		this.ensureReadyNotification();
	}
	
	loadMusicData(sampleRate, path, filename, data, options)
	{
		filename = this._getFilename(path, filename);

		let ret = this.Module.ccall('emu_load_file', 'number',
							['string', 'number', 'number', 'number', 'number', 'number'],
							[ filename, 0, 0, ScriptNodePlayer.getWebAudioSampleRate(), -999, false]);

		if (ret == 0) {
			this._setupOutputResampling(sampleRate);
		}
		return ret;
	}

	evalTrackOptions(options)
	{
		super.evalTrackOptions(options);

		let boostVolume = (options && options.boostVolume) ? options.boostVolume : 0;
		this.Module.ccall('emu_set_boost', 'number', ['number'], [boostVolume]);

		// no subsongs in this format
		return 0;
	}

	getSongInfoMeta()
	{
		return {
			title: String,
			artist: String,
			game: String,
			year: String,
			genre: String,
			copyright: String,
			psfby: String
		};
	}

	updateSongInfo(filename)
	{
		let result = this._songInfo;
		
		let numAttr = 7;
		let ret = this.Module.ccall('emu_get_track_info', 'number');

		let array = this.Module.HEAP32.subarray(ret>>2, (ret>>2)+numAttr);
		result.title = this.Module.Pointer_stringify(array[0]);
		if (!result.title.length) result.title = filename.replace(/^.*[\\\/]/, '');
		result.artist = this.Module.Pointer_stringify(array[1]);
		result.game = this.Module.Pointer_stringify(array[2]);
		result.year = this.Module.Pointer_stringify(array[3]);
		result.genre = this.Module.Pointer_stringify(array[4]);
		result.copyright = this.Module.Pointer_stringify(array[5]);
		result.psfby = this.Module.Pointer_stringify(array[6]);
	}
};
